### ISSUE TITLE
Code please?

### ISSUE THREAD

**Issue by complexgenome** [richardslab/Ei#1]
Hi there,

I'd be interested to implement gene index described in the paper.

https://www.biorxiv.org/content/10.1101/2020.06.28.171561v1.full.pdf

**Comment by jameskozubek** [comment]
Me too. We are interested in your code.

**Comment by richardslab** [comment]
Hi, sorry for the delay. The plan is to release code to run prediction on new triats in the coming week or two, followed by more full code to trains new models in the week or two that follows.

**Comment by richardslab** [comment]
Code is released.
